name: Daily Postman Tests & Email Report

on:
  schedule:
    - cron: '0 14 * * *'  # 8:00 PM IST (UTC+5:30)
  workflow_dispatch:       # Optional manual trigger

jobs:
  test-and-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection and Generate HTML Report
      run: |
        newman run collections/Test_Collection.postman_collection \
          -e environments/Test_Env.postman_environment \
          -r cli,html \
          --reporter-html-export report.html

    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 🚀 Daily Postman Test Report
        body: |
          Hello Team,

          The daily Postman API tests have completed. Please find the attached HTML report.

          Regards,
          GitHub CI
        to: ${{ secrets.EMAIL_TO }}
        from: Postman CI Bot <${{ secrets.EMAIL_USERNAME }}>
        attachments: report.html
